import React from 'react';
import { Bike, CheckCircle2, AlertCircle } from 'lucide-react';
import { SchoolieIcon } from '../components/Common/Icons';

interface MPLHAIDrawerProps {
  dateRange: string;
}

export const MPLHAIDrawer: React.FC<MPLHAIDrawerProps> = ({ dateRange }) => {
  return (
    <div className="animate-in slide-in-from-bottom-4 duration-500 text-left">
      {/* 1. Conversational Summary (Outside the white card) */}
      <p className="text-gray-600 mb-6 px-1 leading-relaxed text-sm">
        This analysis was generated for all sites in the Mercer County District 
        for the dates between {dateRange} regarding Meals Per Labor Hour efficiency.
      </p>

      {/* 2. The AI Analysis Card */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 max-w-none">
        <h2 className="text-xl font-bold text-gray-900 mb-2">MPLH Analysis</h2>
        <p className="text-gray-600">
          Based on current labor hours and meal equivalents for {dateRange}, 
          the district is currently performing 1.62 points below the benchmark.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
          <div className="p-4 bg-green-50 rounded-lg border border-green-100 relative overflow-hidden">
            <CheckCircle2 className="absolute -right-2 -top-2 w-12 h-12 text-green-100" />
            <h4 className="text-green-800 mt-0 font-bold mb-2 text-sm">What's Working</h4>
            <p className="text-sm text-green-700 relative z-10">
              High School sites are exceeding benchmarks by +1.37 through efficient staggered service times.
            </p>
          </div>

          <div className="p-4 bg-amber-50 rounded-lg border border-amber-100 relative overflow-hidden">
            <AlertCircle className="absolute -right-2 -top-2 w-12 h-12 text-amber-100" />
            <h4 className="text-amber-800 mt-0 font-bold mb-2 text-sm">Needs Attention</h4>
            <p className="text-sm text-amber-700 relative z-10">
              Middle Schools are the primary drag on efficiency (-3.13), likely due to overstaffing in prep periods.
            </p>
          </div>
        </div>

        <p className="text-xs text-gray-400 mt-8 italic pt-4 flex justify-between border-t border-gray-50">
          <span>Analysis generated by Schoolie AI</span>
          <span>{new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
        </p>
      </div>
    </div>
  );
};